/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import TableClasses.Airplane;
import TableClasses.Airport;
import TableClasses.ConnectionManager;
import TableClasses.Flight_leg;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class AddLeg extends javax.swing.JFrame {

    /**
     * Creates new form AddLeg
     */
    public AddLeg() {
        initComponents();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionManager cm= new ConnectionManager();
            Connection mycon= DriverManager.getConnection(cm.getUrl(), cm.getU(), cm.getP());
            Statement stmt = mycon.createStatement();            
            ResultSet myrs = stmt.executeQuery(String.format("Select name from Airport"));            
            while(myrs.next()){
                CBdair.addItem(myrs.getString("name"));
                CBaair.addItem(myrs.getString("name"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_fl = new javax.swing.JTable();
        Bview = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TFlegnum = new javax.swing.JTextField();
        bdelete = new javax.swing.JButton();
        bfetch = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TFflightnum = new javax.swing.JTextField();
        TFdtime = new javax.swing.JTextField();
        TFatime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TFdist = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CBstats = new javax.swing.JComboBox<>();
        badd = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TFcost = new javax.swing.JTextField();
        CBdair = new javax.swing.JComboBox<>();
        CBaair = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Flight Legs");

        table_fl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Leg Number", "Flight Number", "Departure", "Arrival", "Departure Time", "Arrival Time", "Available Seats", "Status", "Cost"
            }
        ));
        jScrollPane1.setViewportView(table_fl);

        Bview.setText("View All");
        Bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BviewActionPerformed(evt);
            }
        });

        jLabel2.setText("Leg Number");

        TFlegnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFlegnumActionPerformed(evt);
            }
        });

        bdelete.setText("Delete");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });

        bfetch.setText("Fetch Details");
        bfetch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfetchActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Departure Airport");

        jLabel5.setText("Flight Number");

        jLabel6.setText("Arrival Airport");

        jLabel7.setText("Departure Time");

        jLabel8.setText("Arrival Time");

        TFflightnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFflightnumActionPerformed(evt);
            }
        });

        TFdtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdtimeActionPerformed(evt);
            }
        });

        TFatime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFatimeActionPerformed(evt);
            }
        });

        jLabel10.setText("Distance");

        TFdist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFdistActionPerformed(evt);
            }
        });

        jLabel11.setText("Status");

        CBstats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVE", "SCHEDULED", "DELAYED", "DEPARTED", "LANDED", "IN_AIR", "ARRIVED", "CANCELLED", "DIVERTED", "UNKNOWN" }));

        badd.setText("Add");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });

        bupdate.setText("Update");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        jLabel12.setText("Cost");

        TFcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFcostActionPerformed(evt);
            }
        });

        CBdair.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBdairItemStateChanged(evt);
            }
        });
        CBdair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBdairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TFlegnum, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bfetch)
                        .addGap(18, 18, 18)
                        .addComponent(bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFflightnum, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFdist, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CBdair, 0, 162, Short.MAX_VALUE)
                                            .addComponent(CBaair, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(176, 176, 176)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TFcost, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(TFatime, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(TFdtime, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(badd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(52, 52, 52)
                                            .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)
                                            .addComponent(CBstats, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(79, 79, 79)))
                                    .addGap(100, 100, 100))))
                        .addContainerGap(229, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(400, 400, 400)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(Bview, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 815, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bview)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFlegnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdelete)
                    .addComponent(bfetch))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFflightnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CBdair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(TFdtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(TFatime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBaair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(TFdist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(TFcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CBstats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(badd)
                    .addComponent(bupdate))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BviewActionPerformed
        Flight_leg fl= new Flight_leg();
        Airplane aplane = new Airplane();
        Airport aport = new Airport();
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionManager cm= new ConnectionManager();
            Connection mycon= DriverManager.getConnection(cm.getUrl(), cm.getU(), cm.getP());
            Statement stmt = mycon.createStatement();
            DefaultTableModel mod= (DefaultTableModel)table_fl.getModel();
            ResultSet myrs = stmt.executeQuery(String.format("Select * from flight_legs"));
            mod.setRowCount(0);
            while(myrs.next()){
               aplane.check_by_num(Integer.parseInt(myrs.getString("flight_num")));
                Object[] row= new Object[10];
                row[0]=myrs.getString("leg_num");
                row[1]=myrs.getString("flight_num");
                row[2]=aport.get_airportLoc_byNum(myrs.getInt("departure_airport"));
                row[3]=aport.get_airportLoc_byNum(myrs.getInt("arrival_airport"));;
                row[4]=myrs.getString("departure_time");
                row[5]=myrs.getString("arrival_time");
                row[6]=myrs.getString("avail_seats");
                row[7]=myrs.getString("distance");
                row[8]=myrs.getString("flight_status");
                row[9]=myrs.getString("cost");
                mod.addRow(row);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BviewActionPerformed

    private void TFlegnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFlegnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFlegnumActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        Flight_leg fl= new Flight_leg();
        String leg = TFlegnum.getText().trim();
        if (leg.length() == 0) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Enter Valid Leg Number");
        	return;
        }
        Is_number chk = new Is_number();
        if (!chk.is_num(leg)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Leg Number not valid");
            return;
        }
        fl.setleg_num(Integer.parseInt(leg));
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionManager cm= new ConnectionManager();
            Connection mycon= DriverManager.getConnection(cm.getUrl(), cm.getU(), cm.getP());
            Statement stmt = mycon.createStatement();               
            stmt.executeUpdate(String.format("delete from flight_legs where leg_num='%s'" ,fl.getleg_num()));
            JOptionPane.showMessageDialog(AddLeg.this, "Deleted. Refresh to view the changes");
            return;                        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
        AdminDash ad= new AdminDash();
        ad.setVisible(true);
        return;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TFflightnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFflightnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFflightnumActionPerformed

    private void TFdtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFdtimeActionPerformed

    private void TFatimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFatimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFatimeActionPerformed

    private void TFdistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFdistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFdistActionPerformed

    private void bfetchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfetchActionPerformed
        Flight_leg fl= new Flight_leg();
        Airplane aplane = new Airplane();
        Airport aport = new Airport();
        String leg = TFlegnum.getText().trim();
        Is_number chk = new Is_number();
        if (leg.length() == 0) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Enter Valid Leg Number");
        	return;
        }
        if (!chk.is_num(leg)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Leg Number not valid");
            return;
        }
        fl.setleg_num(Integer.parseInt(leg));
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionManager cm= new ConnectionManager();
            Connection mycon= DriverManager.getConnection(cm.getUrl(), cm.getU(), cm.getP());
            Statement stmt = mycon.createStatement();
            ResultSet myrs = stmt.executeQuery(String.format("Select * from flight_legs where leg_num='%s'",fl.getleg_num()));
            if(myrs.next()){
                //TFaair.setText(aport.get_airportLoc_byNum(myrs.getInt("arrival_airport")));
                TFatime.setText(myrs.getString("arrival_time"));
                //TFdair.setText(aport.get_airportLoc_byNum(myrs.getInt("departure_airport")));
                TFdist.setText(myrs.getString("distance"));
                TFdtime.setText(myrs.getString("departure_time"));
                TFflightnum.setText(myrs.getString("flight_num"));
                TFcost.setText(myrs.getString("cost"));
                CBstats.setSelectedItem(myrs.getString("flight_status"));
                CBaair.setSelectedItem(aport.get_airportLoc_byNum(myrs.getInt("arrival_airport")));
                CBdair.setSelectedItem(aport.get_airportLoc_byNum(myrs.getInt("departure_airport")));
                return;
                
            }
            JOptionPane.showMessageDialog(AddLeg.this, "Enter Valid Number");
                return;

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bfetchActionPerformed
    
    
    
    private Boolean lies_between(String StartA , String EndA , String StartB , String EndB) {
    	
    	if ((StartA.compareTo(StartB) > 0 ? StartA: StartB).compareTo((EndA.compareTo(EndB) < 0? EndA: EndB)) <= 0)return true;
    	return false;
    }
    
    private Boolean duplicate_flights(Flight_leg fl) {
    	String [] status = {"ACTIVE" , "SCHEDULED" , "DELAYED" , "DEPARTED" , "IN_AIR"};
    	int flag = 0;
    	for (String stat : status) {
    		if (fl.Flight_status == stat) {
    			flag = 1;
    			break;
    		}
    	}
    	if (flag == 0) {
    		return false;
    	}
    	try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionManager cm= new ConnectionManager();
            Connection mycon= DriverManager.getConnection(cm.getUrl(), cm.getU(), cm.getP());
            Statement stmt = mycon.createStatement();
            ResultSet myrs = stmt.executeQuery(String.format("Select arrival_time , departure_time  from(Select arrival_time , departure_time , flight_status from Flight_legs where flight_num = %d) as fl where flight_status in ('ACTIVE' , 'SCHEDULED' , \"DELAYED\" , \"DEPARTED\" , \"IN_AIR\") ;"  , fl.flightNumber )) ;
            flag = 0;
            while(myrs.next()) {
            	String arrival = myrs.getString("arrival_time") ;
            	String depart = myrs.getString("departure_time");
            	if (flag == 0 && arrival.equals(fl.arrival_time) && depart.equals(fl.departure_time)) {
            		flag = 1;
            		continue;
            	}
            	System.out.printf("%s %s %s %s\n" , fl.arrival_time , fl.departure_time , arrival , depart);
            	if (lies_between(fl.departure_time , fl.arrival_time , depart , arrival) ) {
            		return true;
            	}
            }
            return false;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    	return true;
    }
    
    
    
    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
        Flight_leg fl= new Flight_leg();
        Airplane aplane = new Airplane();
        Airport aport = new Airport();
        Is_number chk = new Is_number();
        String fl_num = TFflightnum.getText().trim();
        if (!chk.is_num(fl_num)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Check Airplane number");
        	return;
        }
        fl.setFlightNumber(Integer.parseInt(fl_num));
        if(!aplane.check_by_num(fl.getFlightNumber()) ){
            JOptionPane.showMessageDialog(AddLeg.this, "No plane found");
        }
        fl.setArrival(aport.get_airportnum_byName(CBaair.getSelectedItem().toString()));
        fl.setDeparture(aport.get_airportnum_byName(CBdair.getSelectedItem().toString()));
        fl.setArrival_time(TFatime.getText().trim());
        fl.setDeparture_time(TFdtime.getText().trim());
        
        String cost = TFcost.getText().trim();
        if (!chk.is_num(cost)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Check the Cost field");
            return;
        }
        fl.setcost(Integer.parseInt(cost));
        String dist = TFdist.getText().trim();
        dist.replaceAll("\\s", "");
        if (!chk.is_num(dist)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Check the Distance field");
            return;
        }
        fl.setDistance(Integer.parseInt(dist));
        fl.setFlight_status(CBstats.getSelectedItem().toString());
        if(fl.getArrival()==-1|| fl.getDeparture()==-1){
            JOptionPane.showMessageDialog(AddLeg.this, "No Airports found");
            return;
        }
        if (fl.arrival == fl.departure) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Arrival and Departure airports must be different");
            return;
        }
        Date_checker chck = new Date_checker();
        time_check check = new time_check();
        if ((fl.arrival_time.length() != 19 || fl.departure_time.length() != 19 )) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Time must be in the format (YYYY-MM-DD HH:MI:SS) and must be a valid date");
        	return;
        }
        System.out.println(fl.arrival_time);
        System.out.println(fl.departure_time);
    
        if ( (chck.date_checker(fl.arrival_time.substring(0 , 10)) != true || chck.date_checker(fl.departure_time.substring(0 , 10)) != true || check.time_check(fl.arrival_time.substring(11 , 19)) != true || check.time_check(fl.departure_time.substring(11 , 19)) != true ) ) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Time Must be in the format (YYYY-MM-DD HH:MI:SS) and must be a valid date");
        	return;
        }
        
        if (fl.arrival_time.compareTo(fl.departure_time) <= 0){
        	JOptionPane.showMessageDialog(AddLeg.this, "Arrival time must be greater than the departure time");
        	return;
        }
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionManager cm= new ConnectionManager();
            Connection mycon= DriverManager.getConnection(cm.getUrl(), cm.getU(), cm.getP());
            Statement stmt = mycon.createStatement();               
            stmt.executeUpdate(String.format("insert into flight_legs(flight_num, Arrival_Airport, departure_airport, flight_status,distance, arrival_time , departure_time, avail_seats,cost) values('%s','%s','%s','%s','%s','%s','%s','%s','%s')" ,fl.getFlightNumber(),fl.getArrival(),fl.getDeparture(),fl.getFlight_status(),fl.getDistance(),fl.getArrival_time(),fl.getDeparture_time(),aplane.getMaximum_occupancy(),fl.getcost()));
            JOptionPane.showMessageDialog(AddLeg.this, "Added");
            if (duplicate_flights(fl) == true){
            	JOptionPane.showMessageDialog(AddLeg.this, "There are two or more flight legs for the same flight during the same time interval.Delete one of them");
            	return;
            }
            return;                    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_baddActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        Flight_leg fl= new Flight_leg();
        Airplane aplane = new Airplane();
        Airport aport = new Airport();
        Is_number chk = new Is_number();
        String leg_num = TFlegnum.getText().trim();
        if (!chk.is_num(leg_num)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Leg Number not valid");
            return;
        }
        fl.setleg_num(Integer.parseInt(leg_num));
        String fligt_num = TFflightnum.getText().trim();
        if (!chk.is_num(fligt_num)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Flight Number not valid");
            return;
        }
        fl.setFlightNumber(Integer.parseInt(fligt_num));
        if(!aplane.check_by_num(fl.getFlightNumber())){
            JOptionPane.showMessageDialog(AddLeg.this, "No plane found");
            return;
        }
        
        fl.setArrival(aport.get_airportnum_byName(CBaair.getSelectedItem().toString()));
        fl.setDeparture(aport.get_airportnum_byName(CBdair.getSelectedItem().toString()));
        fl.setArrival_time(TFatime.getText().trim());
        fl.setDeparture_time(TFdtime.getText().trim());
        String cost = TFcost.getText().trim();
        if (!chk.is_num(cost)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Cost not valid");
            return;
        }
        fl.setcost(Integer.parseInt(cost));
        String dist = TFdist.getText().trim();
        if (!chk.is_num(dist)) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Distance not valid");
            return;
        }
        fl.setDistance(Integer.parseInt(dist));
        fl.setFlight_status(CBstats.getSelectedItem().toString());
        if(fl.getArrival()==-1|| fl.getDeparture()==-1){
            JOptionPane.showMessageDialog(AddLeg.this, "No Airports found");
            return;
        }
        if (fl.arrival == fl.departure) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Arrival and Departure airports must be different");
            return;
        }
        Date_checker chck = new Date_checker();
        time_check check = new time_check();
        if ((fl.arrival_time.length() != 19 || fl.departure_time.length() != 19 )) 
        {
        	JOptionPane.showMessageDialog(AddLeg.this, "Time must be in the format (YYYY-MM-DD HH:MI:SS)");
        	return;
        }
        if ((chck.date_checker(fl.arrival_time.substring(0 , 10)) != true || chck.date_checker(fl.departure_time.substring(0 , 10)) != true || check.time_check(fl.arrival_time.substring(11 , 19)) != true || check.time_check(fl.departure_time.substring(11 , 19)) != true ) ) {
        	JOptionPane.showMessageDialog(AddLeg.this, "Time must be in the format (YYYY-MM-DD HH:MI:SS)");
        	return;
        }
        
        	
        
        if (fl.arrival_time.compareTo(fl.departure_time) <= 0){
        	JOptionPane.showMessageDialog(AddLeg.this, "Arrival time must be greater than departure time");
        	return;
        }
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            ConnectionManager cm= new ConnectionManager();
            Connection mycon= DriverManager.getConnection(cm.getUrl(), cm.getU(), cm.getP());
            Statement stmt = mycon.createStatement();               
            stmt.executeUpdate(String.format("update flight_legs set flight_num='%s', Arrival_Airport='%s', departure_airport='%s', flight_status='%s',distance='%s', arrival_time='%s' , departure_time='%s', avail_seats='%s',cost='%s' where leg_num='%s'" ,fl.getFlightNumber(),fl.getArrival(),fl.getDeparture(),fl.getFlight_status(),fl.getDistance(),fl.getArrival_time(),fl.getDeparture_time(),aplane.getMaximum_occupancy(),fl.getcost(),fl.getleg_num()));
            JOptionPane.showMessageDialog(AddLeg.this, "Updated");
            if (duplicate_flights(fl) == true) {
            	JOptionPane.showMessageDialog(AddLeg.this, "There are two or more flight legs for the same flight during the same time interval.Delete one of them");
            	return;
            }
            return;                        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bupdateActionPerformed

    private void TFcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFcostActionPerformed

    private void CBdairItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBdairItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CBdairItemStateChanged

    private void CBdairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBdairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBdairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLeg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLeg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bview;
    private javax.swing.JComboBox<String> CBaair;
    private javax.swing.JComboBox<String> CBdair;
    private javax.swing.JComboBox<String> CBstats;
    private javax.swing.JTextField TFatime;
    private javax.swing.JTextField TFcost;
    private javax.swing.JTextField TFdist;
    private javax.swing.JTextField TFdtime;
    private javax.swing.JTextField TFflightnum;
    private javax.swing.JTextField TFlegnum;
    private javax.swing.JButton badd;
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bfetch;
    private javax.swing.JButton bupdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_fl;
    // End of variables declaration//GEN-END:variables
}
